# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('alias', models.CharField(max_length=255, verbose_name='Alias категории')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.IntegerField(default=0, verbose_name='Цена товара')),
                ('image', models.CharField(max_length=255, verbose_name='Ссылка на картинку')),
                ('number', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('description', models.CharField(max_length=255, verbose_name='Описание товара')),
                ('alias', models.CharField(max_length=255, verbose_name='Alias товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
            ],
        ),
    ]
