# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Nickname')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('text', models.CharField(max_length=300, verbose_name='Text')),
                ('amount', models.FloatField(verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
        migrations.CreateModel(
            name='ReqToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=25, verbose_name='Key')),
                ('isUsed', models.BooleanField(verbose_name='isUsed')),
                ('DonationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Donation')),
            ],
            options={
                'verbose_name': 'ReqToken',
                'verbose_name_plural': 'ReqTokens',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Word')),
                ('image', models.ImageField(max_length=400, upload_to='', verbose_name='Image')),
                ('pathArray', models.SlugField(verbose_name='PathArray')),
                ('CurrentStatus', models.CharField(max_length=15, verbose_name='Current Status')),
                ('DonationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Donation')),
                ('TokenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ReqToken')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, verbose_name='Username')),
                ('RequestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Request')),
            ],
            options={
                'verbose_name': 'Winner',
                'verbose_name_plural': 'Winners',
            },
        ),
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
